blank_issues_enabled: false
contact_links:
  - name: Sporsmal om arrangementer
    url: https://github.com/orgs/bouvet/discussions
    about: Kontakt admin eller bruk Discussions hvis du trenger hjelp med innmelding.